const dummyPostCardData = [
  {
    PoemId: 1,
    PoemTitle: "Whispers of the Wind",
    PoemStartContent: "In the quiet of the night, whispers of the wind,",
    PoetName: "Emily Dickinson",
    NumberOfLikes: 120,
  },
  {
    PoemId: 2,
    PoemTitle: "The Road Not Taken",
    PoemStartContent: "Two roads diverged in a yellow wood,",
    PoetName: "Robert Frost",
    NumberOfLikes: 250,
  },
  {
    PoemId: 3,
    PoemTitle: "If You Forget Me",
    PoemStartContent: "I want you to know one thing.",
    PoetName: "Pablo Neruda",
    NumberOfLikes: 180,
  },
  {
    PoemId: 4,
    PoemTitle: "Annabel Lee",
    PoemStartContent: "It was many and many a year ago,",
    PoetName: "Edgar Allan Poe",
    NumberOfLikes: 300,
  },
  {
    PoemId: 5,
    PoemTitle: "A Dream Within a Dream",
    PoemStartContent: "Take this kiss upon the brow!",
    PoetName: "Edgar Allan Poe",
    NumberOfLikes: 210,
  },
  {
    PoemId: 6,
    PoemTitle: "Sonnet 18: Shall I compare thee to a summer's day?",
    PoemStartContent: "Shall I compare thee to a summer's day?",
    PoetName: "William Shakespeare",
    NumberOfLikes: 320,
  },
  {
    PoemId: 7,
    PoemTitle: "Invictus",
    PoemStartContent: "Out of the night that covers me,",
    PoetName: "William Ernest Henley",
    NumberOfLikes: 290,
  },
  {
    PoemId: 8,
    PoemTitle: "Stopping by Woods on a Snowy Evening",
    PoemStartContent: "Whose woods these are I think I know,",
    PoetName: "Robert Frost",
    NumberOfLikes: 230,
  },
  {
    PoemId: 9,
    PoemTitle: "I Wandered Lonely as a Cloud",
    PoemStartContent: "I wandered lonely as a cloud",
    PoetName: "William Wordsworth",
    NumberOfLikes: 270,
  },
  {
    PoemId: 10,
    PoemTitle: "The Raven",
    PoemStartContent:
      "Once upon a midnight dreary, while I pondered, weak and weary,",
    PoetName: "Edgar Allan Poe",
    NumberOfLikes: 350,
  },
  {
    PoemId: 11,
    PoemTitle: "Hope is the thing with feathers",
    PoemStartContent: "Hope is the thing with feathers",
    PoetName: "Emily Dickinson",
    NumberOfLikes: 180,
  },
  {
    PoemId: 12,
    PoemTitle: "Do Not Go Gentle into That Good Night",
    PoemStartContent: "Do not go gentle into that good night,",
    PoetName: "Dylan Thomas",
    NumberOfLikes: 320,
  },
  {
    PoemId: 13,
    PoemTitle: "Fire and Ice",
    PoemStartContent: "Some say the world will end in fire,",
    PoetName: "Robert Frost",
    NumberOfLikes: 290,
  },
  {
    PoemId: 14,
    PoemTitle: "She Walks in Beauty",
    PoemStartContent: "She walks in beauty, like the night",
    PoetName: "Lord Byron",
    NumberOfLikes: 260,
  },
  {
    PoemId: 15,
    PoemTitle: "A Dream Within a Dream",
    PoemStartContent: "Take this kiss upon the brow!",
    PoetName: "Edgar Allan Poe",
    NumberOfLikes: 210,
  },
  {
    PoemId: 16,
    PoemTitle: "If",
    PoemStartContent: "If you can keep your head when all about you",
    PoetName: "Rudyard Kipling",
    NumberOfLikes: 300,
  },
  {
    PoemId: 17,
    PoemTitle: "O Captain! My Captain!",
    PoemStartContent: "O Captain! my Captain! our fearful trip is done,",
    PoetName: "Walt Whitman",
    NumberOfLikes: 350,
  },
  {
    PoemId: 18,
    PoemTitle: "The Love Song of J. Alfred Prufrock",
    PoemStartContent: "Let us go then, you and I,",
    PoetName: "T. S. Eliot",
    NumberOfLikes: 240,
  },
  {
    PoemId: 19,
    PoemTitle: "The Tyger",
    PoemStartContent: "Tyger Tyger, burning bright,",
    PoetName: "William Blake",
    NumberOfLikes: 280,
  },
  {
    PoemId: 20,
    PoemTitle: "Jabberwocky",
    PoemStartContent: "'Twas brillig, and the slithy toves",
    PoetName: "Lewis Carroll",
    NumberOfLikes: 190,
  },
  {
    PoemId: 21,
    PoemTitle: "To Autumn",
    PoemStartContent: "Season of mists and mellow fruitfulness,",
    PoetName: "John Keats",
    NumberOfLikes: 320,
  },
  {
    PoemId: 22,
    PoemTitle: "The Waste Land",
    PoemStartContent: "April is the cruellest month, breeding",
    PoetName: "T. S. Eliot",
    NumberOfLikes: 280,
  },
  {
    PoemId: 23,
    PoemTitle: "Annabel Lee",
    PoemStartContent: "It was many and many a year ago,",
    PoetName: "Edgar Allan Poe",
    NumberOfLikes: 300,
  },
];

module.exports = dummyPostCardData;
